{% set version = "3.0.0" %}

package:
  name: geojson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geojson/geojson-{{ version }}.tar.gz
  sha256: ea1df8246bdeb2bbf20d0756720911893414f9cee46b336a1e882d2cd60cfba1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - geojson

about:
  home: https://github.com/frewsxcv/python-geojson
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Python bindings and utilities for GeoJSON

extra:
  recipe-maintainers:
    - ocefpaf
