{% set name = "geojson" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geojson-{{ version }}.tar.gz
  sha256: 58a7fa40727ea058efc28b0e9ff0099eadf6d0965e04690830208d3ef571adac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - geojson
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/frewsxcv/python-geojson
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Python bindings and utilities for GeoJSON

extra:
  recipe-maintainers:
    - ocefpaf
