{% set name = "geojson" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geojson-{{ version }}.tar.gz
  sha256: ff3d75acab60b1e66504a11f7ea12c104bad32ff3c410a807788663b966dee4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12

test:
  imports:
    - geojson
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/frewsxcv/python-geojson
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Python bindings and utilities for GeoJSON

extra:
  recipe-maintainers:
    - ocefpaf
